### ISSUE TITLE
All images goes 404

### ISSUE THREAD

**Issue by man4toman** [wptrainingteam/basic-theme-configuration#3]
Hi @JulieKuehl 
All images in lesson are 404. 
Are they screenshot?
If they are screenshot I can start add new images instead them.

**Comment by JulieKuehl** [comment]
They likely were all screenshots and will need to be replaced. These missing images are what precipitated our move to GitHub. It would be fantastic to have them (or new, better ones) back again!

**Comment by man4toman** [comment]
Sure, I will replace them.
